# 应用名称
spring:
  application:
    name: nacos-spring-boot
nacos:
  config:
    server-addr: 127.0.0.1:8848
    data-id: nacos-spring-boot
    auto-refresh: true
    type: yaml
    bootstrap:
      enable: true
    group: operation
my:
  test:
    appId: testAppId
    userName: appid
    password: appid